site_name: Seiri
copyright: >
  Copyright &copy; 2023
  <a href="http://seiri.blog">seiri's blog</a>

site_url: http://seiri.blog
repo_url: https://github.com/seiri-blog/Wiki
site_description: seiri's blog
site_author: seiri

nav:
  - トップ: index.md
  - ブログ: http://seiri.blog
  - プロファイル: http://seiri.blog/profile
  - アーカイブ: http://seiri.blog/profile
  - 問合せ: dissusion.md

theme:
  name: material
  custom_dir: overrides
  logo: http://seiri.blog/favicon.ico
  favicon: http://seiri.blog/favicon.ico
  language: ja
  # font:
  #   text: Roboto
  #   code: Roboto Mono

  include_search_page: false
  search_index_only: true
  palette:
    - media: "(prefers-color-scheme: light)"
      primary: white
      scheme: default
      toggle:
        icon: asserts/material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: black
      scheme: slate
      toggle:
        icon: asserts/material/weather-sunny
        name: Switch to light mode
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - toc.follow
    # - toc.integrate
    - navigation.top
    # - announce.dismiss
    - search.suggest
    - search.highlight
    - search.share
    - header.autohide
    - announce.dismiss
    - content.code.annotate
social:
  - icon: "asserts/fontawesome/brands/github"
    link: "https://github.com/Ryuseiri"
markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra_css:
  - asserts/stylesheets/extra.css
