site_name: Salesforce Trailhead Superbadge 日本語訳
copyright: >
  Copyright &copy; 2023
  <a href="https://seiri.blog">seiri's blog</a>
site_description: >
  Salesforce の Trailhead Superbadge (スーパーバッジ) の日本語訳です。公式の日本語訳(☁️)へのリンクも含みます。
  原文のアップデートは予告なく行われるため、翻訳が追いつかない場合がありますがご容赦ください。
site_author: seiri
nav:
  - Superbadge記事一覧: index.md
  - プロファイル: profile.md
  - ブログ: https://seiri.blog
  - アーカイブ: https://seiri.blog/archives
extra:
  homepage: https://seiri.blog/wiki/
  generator: false
  consent:
    title: Salesforce Trailhead Superbadge 日本語訳
    description: >- 
      Salesforce の Trailhead Superbadge (スーパーバッジ) の日本語訳です。公式の日本語訳(☁️)へのリンクも含みます。
      原文のアップデートは予告なく行われるため、翻訳が追いつかない場合がありますがご容赦ください。   
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Ryuseiri
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/people/Ryu-Seiri/100087864783411
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/Seiriryu
    - icon: fontawesome/brands/quora
      link: https://qiita.com/Seiri
    - icon: fontawesome/brands/blogger
      link: https://knowstechnic.blogspot.com
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCph3vDUIHt68iR0vtHbChaw
    - icon: fontawesome/brands/bootstrap
      link: https://space.bilibili.com/140506788
theme:
  name: material
  custom_dir: overrides
  logo: https://seiri.blog/favicon.ico
  favicon: https://seiri.blog/favicon.ico
  language: ja

  include_search_page: false
  search_index_only: true
  palette:
    - media: "(prefers-color-scheme: light)"
      primary: white
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: black
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.footer
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - toc.follow
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - header.autohide
    - announce.dismiss
    - content.code.annotate
  plugins: 
    - meta
    - blog:
        blog_toc: true
        enabled: true
        blog_dir: posts
    - search
    - tags
    - rss:
      match_path: posts/.* 
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags 

  
markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra_css:
  - assets/stylesheets/extra.css
